### ISSUE TITLE
Missing description on action icons

### ISSUE THREAD

**Issue by reflectionalist** [emersion/firefox-passwordmaker#11]
No description is provided for the action icons.  So it is unclear what actions are triggered on clicking.  For example, I do not know where the master password is saved when I click on the save icon.  The online version provide options like "save to memory", "save to disk", or something like that.  Such options are not available in the settings of the addon.  It is also unknown what action the arrow icon triggers when clicked.

**Comment by emersion** [comment]
What's strange is that the `title` attribute is set, so it should display a tooltip on hover (see https://github.com/emersion/firefox-passwordmaker/blob/master/data/panel.html#L14). I'll see why it's not working.

**Comment by emersion** [comment]
Fixed in v0.11 ;-)
