### ISSUE TITLE
Include time stamp when generating passwords

### ISSUE THREAD

**Issue by reflectionalist** [emersion/firefox-passwordmaker#13]
I just realized a problem with PasswordMaker and PasswordGen.  Both use relatively invariant inputs, usually domain, subdomain, etc., to generate passwords.  If I understand how PM and PG work correctly, for the same domain (in combination with the master password, which presumably is constant), they generate the same password.  Then in one scenario, PM and PG would not suit.  Some websites (e.g., ymail.com, the web mail provided by Yahoo), for secuity reasons, do not allow the user to use previously-used passwords when he wants to change his password for whatever reason.  If the old password he wants to change was generated by PM or PG, then PM or PG could not generate a new random password given that the domain and the master password are the same!

I suggest one solution to this problem.  When PM generates a password, take as input also the time stamp.  Afterwards, save the time stamp for that domain (saving time stamp is fine).  This time stamp should be protected from accidental modification since it will be used to regenerate the same password.  However, when the user does want to change the old password for those websites mentioned above, PG generates a new password with the a time stamp (and overwrite the old time stamp).

**Comment by emersion** [comment]
The goal of PasswordMaker is to be able to recover password even if you loose all your devices.

A solution to this problem would be to add per-site settings to this extension and change the prefix/suffix/modifier (see #4).
