### ISSUE TITLE
Password Maker does not work in Firefox 40.0.3

### ISSUE THREAD

**Issue by Auronius** [emersion/firefox-passwordmaker#15]
Good Day! I am using Firefox 40.0.3, and after installing Password Maker I can not see the programs icon (yellow ring). Also I can not set it to the browsers taskpanel because it`s not available. 
Also keyboard shortcut for lauching a program does not working. Please fix it. Seems like your addon is not compatible with latest Firefox version...

**Comment by emersion** [comment]
Hi,

I'm using Firefox 40.0.3 and the addon is working properly. Did you double-check that the addon is enabled?

**Comment by Auronius** [comment]
Yes, here is a video, which proves, that in my Firefox browser this addon does not working.
https://youtu.be/_0s_uw_rImk

**Comment by emersion** [comment]
Thanks for the video, that's quite strange! The empty button label is "Password Maker (c", can you drag your mouse over it to see the full label in a tolltip please?

**Comment by Auronius** [comment]
It does not show the full label. Only "Password Maker (c..." Dragging and moving does not help.

**Comment by Auronius** [comment]
Tested on Windows XP, Firefox 40.0.3 and still addon is not working :(

**Comment by emersion** [comment]
Tried to reproduce on multiple computers (Archlinux/elementary/Windows/OS X) and could not reproduce. Can you try to disable all your addons and reinstall Password Maker ?

**Comment by Auronius** [comment]
Completely removed and reinstalled Firefox. Add-on started to work. Sorry for wasting your time. Should do it before creating a topic.

**Comment by emersion** [comment]
Good to hear, no problem! :-)

**Comment by emersion** [comment]
This is quite strange that this setting makes the add-on not to work anymore. Do you have any clue?

**Comment by emersion** [comment]
Maybe because of Firefox's policy with addons in private mode (private window and "Do not remember history" are the same thing, one temporary, one permanent). Then this is a real issue. I'll investigate.

**Comment by Auronius** [comment]
I will make video tomorrow if you need.

**Comment by emersion** [comment]
Thanks, but I think I won't need it. According to the docs, it is a normal behaviour that addons stop working in private mode. Addons must opt-in to continue to work.

**Comment by emersion** [comment]
I just published v1.0.0 which adds support for private browsing mode. You can install it from here: https://addons.mozilla.org/fr/firefox/addon/password-maker-x/versions/ ;-)

**Comment by Auronius** [comment]
Thank you! Working good!

**Comment by Auronius** [comment]
Dot`t want create topic for one question.
If not to click on save button, master password is temporarily stored in RAM or in browsers cache? And how long does it stored?

**Comment by emersion** [comment]
The password is stored in RAM, and is cleared when the browser is restarted.
