### ISSUE TITLE
No icon in the addon manager

### ISSUE THREAD

**Issue by Auronius** [emersion/firefox-passwordmaker#17]
Good day! In Add-ons list there is no orange circle before Password Maker X.
http://imgur.com/a5iEaCF
Everything else works good! Thank you for Great add-on!

**Comment by emersion** [comment]
You're right, I'll see why the icon is not displayed :-)

BTW, thanks for your review!

**Comment by emersion** [comment]
Fixed in the latest release.

**Comment by Auronius** [comment]
I am sorry, but where is the latest release? In Firefox extension lists there is only version 1.0.0 is available.

**Comment by emersion** [comment]
Version 1.1 had some problems with unicode chars, so I removed it. I just submitted version 2.0, which is a complete library rewrite (but there is no visible change for the user). Older algos have been removed in this release.

**Comment by Auronius** [comment]
Good to hear! Thank you!

**Comment by Auronius** [comment]
Just tested version 2.0.0, works good! Installed from this page: https://addons.mozilla.org/fr/firefox/addon/password-maker-x/versions/
