### ISSUE TITLE
Add a way to check that the master password is the correct one

### ISSUE THREAD

**Issue by Auronius** [emersion/firefox-passwordmaker#18]
Please add three symbol password Verification Code like in Google chrome extension, created by Eric Aguiar. http://imgur.com/zSUMTXn
These three symbols are generated automatically based on typed master password. They offer ability to check, if the master password has been typed correctly or not without showing it.

**Comment by emersion** [comment]
I would prefer something like [unicornpass](https://github.com/carmebar/unicornpass), but it's basically the same idea.

**Comment by emersion** [comment]
Fixed in https://github.com/emersion/passwordmaker
