### ISSUE TITLE
ripemd160 not generating passwords in FF 43 for Ubuntu Linux

### ISSUE THREAD

**Issue by neilunderwood** [emersion/firefox-passwordmaker#19]
All of a sudden passwordmaker has stopped generating passwords when I select the hmac-ripemd160 or ripemd160 algorithms.  I just receive a blank password field.  All other algorithms work just fine.  Is this a known issue?

**Comment by emersion** [comment]
Thanks for reporting this bug! Will fix asap ;-)

Quite strange, since all algorithms are now [tested](https://github.com/emersion/node-passwordmaker/blob/master/test/test.js#L69). Must be a UI bug or something.

**Comment by emersion** [comment]
Fixed in f43ee4e7c3071ce57ec3fa8740367c87e21685e9.

You can install it from here: https://addons.mozilla.org/en-US/firefox/addon/password-maker-x/versions/?page=1#version-2.0.1
