### ISSUE TITLE
Integration to Palemoon browser.

### ISSUE THREAD

**Issue by Auronius** [emersion/firefox-passwordmaker#21]
Good Day!
Is it possible to make your Password Maker X compatible with  [Palemoon](http://www.palemoon.org/) browser, which is similar to Firefox but much faster, because does not includes unnecessary things like telemetry, parental controls...and others.

**Comment by emersion** [comment]
Hi! Have you tested to install the .xpi in your browser? If it doesn't works, unforrunately I think this is a won't fix, as Password Maker X uses the add-on SDK, which is maybe not implemented in your browser.

**Comment by Auronius** [comment]
Unfortunately, it is not compatible with Palemoon browser :(
http://itmag.es/21btV

**Comment by emersion** [comment]
Sorry about that! :(

**Comment by Auronius** [comment]
Anyway I left the query in [Palemoons forum](https://forum.palemoon.org/viewforum.php?f=37)for integration.
