### ISSUE TITLE
No settings on phone, different passwords generated

### ISSUE THREAD

**Issue by andypillip** [emersion/firefox-passwordmaker#27]
One great bonus from Passwordmaker is that you can generate your passwords anywhere.

Which is why I'm also using the extension on my phone.

But on the phone there's no _Settings_, and it generates different passwords, probably due to a different setting?

I've been checking `about:config` for settings, and I can find them all under the same _jid1_ as on the desktop, and they are all the same.

But shouldn't the Add-On on the phone have a different jid1?

**Comment by emersion** [comment]
Can you give an example of input + configuration and the two different outputs?

**Comment by andypillip** [comment]
Thanks for getting back to me.

Could you please clarify my question before?
Is it correct that the jid is the same on Desktop and on Phone?

Domain: github.com
Master Password: 12345

Desktop: B511m/37
Phone: B511m/37

hm.

I'm trying to remember the site that didn't let me login on phone, but on desktop.
Maybe the problem actually was a different hostname, because of a mobile redirect?

I guess you can close, I'll comment again when I find the page and can reproduce the issue.

Sorry

**Comment by emersion** [comment]
All right, no problem!

> Is it correct that the jid is the same on Desktop and on Phone?

Yeah, same on desktop and mobile.
